<div class="container center">
<div class="row-fluid">
    <font size="5" align="center" color="red"> Ваш браузер не подходит!</font><br>
    Работа с системой невозможна c браузером Internet Explorer
    <br>
    Мы предлагаем Вам <b>загрузить</b> один из данных браузеров.
    <br>
    <p>
        Для загрузки браузера нажмите на любой из браузеров.
    </p>
    <hr/>
    <hr>
    <a href="http://www.google.ru/intl/ru/chrome/" style="color: white;">
        <img src="/img/browser/chrome.png" title="Пререйти на скачивание Chrome"></a>

    <br>
    <a href="http://www.mozilla.org/ru/firefox/new/" style="color: white;">
        <img src="/img/browser/firefox.png" alt="" title="Пререйти на скачивание Firefox"></a>
<!--    <br>-->
<!--    <a href="http://www.opera.com/ru"  style="color: white;">-->
<!--        <img src="/img/browser/opera.png" alt="" title="Пререйти на скачивание Opera">-->
<!--    </a>-->
    <br>
    <hr>
    После скачивания закройте текущий браузер и повторите вход на новом.
</div>
</div>