<h1>Добавление на кафедру</h1>
<hr>
<div  class="row-fluid" >
    <label class="control-label" for="inputEmail">Выберите кафедру</label>
    <div class="controls">
        <label type='select'>
            <select class="search-query span12" id='login-kaf' type="text">
                <?php foreach($kafedra as $key => $val):  ?>
                    <option name="<?php echo $key; ?>"><?php echo $val; ?></option>
                <?php endforeach; ?>

            </select>
        </label>
    </div>
</div>
<div class="row-fluid">

    <div class="controls">
        <button type="submit" id="append_user_in_kaf" class="btn btn-primary span12">
            <div id="text">Добавиться</div>
        </button>
    </div>
</div>
<script src="/js/user/appendinkaf.js" type="application/javascript"></script>