
<h1>Личный кабинет</h1>
<hr>
<h3></h3>
<div class="row-fluid" id="users_content">

    <div class="controls controls-row">
        <div class="span3">
            <div class="control-group">
                <img style="border-radius: 5px; box-s hadow: 0 0 10px rgba(0,0,0,0.5);" src="./img/empty.jpg">
            </div>
<!--            <i class="icon-edit"></i><a href="--><?php //echo $this->url('user',array('controller'=>'table','action'=>'edit','id_table'=>22,'id'=>$user->id));?><!--">Редактировать</a>-->
               <i class="icon-edit"></i><a href="<?php echo $this->url('user/default',array('action'=>'edit'));?>">Редактировать</a>
        </div>

        <div class="span6">
            <div >
                <ul>
                    <li>Кафедра:
                        <?php if($user->name_kaf != ''): ?>
                        <?php echo $user->name_kaf;?> </li>
                        <?php else: ?>
                        <a ajax-href="<?php echo $this->url("user",array("controller"=>"user","action"=>"appendinkaf")); ?>" href="#" modal="true" content="body"><i class="icon-plus"></i> Добавить кафедру</a>
                        <?php endif; ?>


                    <?php foreach($form_user as $data): ;?>
                        <li><?php echo $data->get('cap') .' : '. $user->get($data->get('cell')); ?>  </li>
                    <?php endforeach; ?>

                </ul>

            </div>
        </div>

    </div>
    <hr>
    <div class="accordion" id="accordion2">
        <div class="accordion-group">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#status">
                    <p>Статус работы: <?php echo $status; ?></p>
                </a>
            </div>

            <div id="status" class="accordion-body collapse">
                <div class="accordion-inner">
                    <div class="well">
                        <p>После нажатия этой кнопки на кафедру поступит информация о том что вы закончили заполнение.
                            В случае ошибок или недочётов в заполнении Вам на почтовый ящик придёт извещение о необходимости доработки.
                            После  внесения поправок необходимо снова нажать на эту кнопку</p>
                        <hr>
                        <form method="post">
                            <button type="submit" class="btn btn-success">Завершить заполнение</button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>




    <div class="row-fluid">

<!--        --><?php //foreach($news as $new):  ?>
<!--                <div class="news" >-->
<!--                    <button id="--><?php //echo $new->id; ?><!--" type="button" class="close" data-dismiss="alert">&times;</button>-->
<!--                    <h4>--><?php //echo $new->cap; ?><!--</h4><time></time>-->
<!--                    <div class="text">-->
<!--                        --><?php //echo $new->text; ?>
<!--                    </div>-->
<!---->
<!--                </div>-->
<!--        --><?php // endforeach; ?>
<?php echo $this->news; ?>

    </div>
</div>


<!--Body content-->
<!--        <div class="span2">-->

<!--            <ul class="nav nav-tabs nav-stacked">-->
<!--                <li class="active"><a href="#"> Главная</a></li>-->
<!--                <li><a ajax-href="--><?php //echo $this->url('user',array('controller'=>'table','action'=>'edit','id_table'=>22,'id'=>$user->id));?><!--" content="#network" href="#">Сообщения</a></li>-->
<!--                <li><a href="#">Справка</a></li>-->
<!--            </ul>-->

<!--        </div>-->
