<h1>Справка</h1>
<hr>
<p>
Эта инструкция призвана помочь научно-педагогическим работникам (НПР)
университета в оформлении ежегодных документов, содержащих результаты и планы научно-исследовательской деятельности.
На сайте КГУ им. Н.А. Некрасова размещена система обработки информации о научно-исследовательской работе (СОИ НИР).
Автоматизированная система не только позволяет избежать ошибок и ускоряет процессы информационного обмена, но и открывает новые
возможности в части информационно-аналитической работы. Однако, как и все новое, данная система помимо благ создает и новые трудности.
Цель этой инструкции - помочь преподавателям научиться пользоваться системой для подготовки документов плана и отчета по НИР.
Использование системы обработки информации не требует глубоких познаний в области компьютерной техники.
</p>


<ul>


    <div class="controls controls-row">
        <div class="span6">
            <h3>Отчёт</h3>
            <ul >
                <li><a cap="Справка" modal="false" content="#help-content" ajax-href="<?php echo $this->url('help', array('action'=>'pages','id'=>'document_reports')); ?>"href="#"> Работа преподавателя с документами отчета</a></li>

                <li><a cap="Справка" ajax-href="<?php echo $this->url('help', array('action'=>'pages','id'=>'themenir')); ?>"  content="#help-content" href="#">Тематический отчет по НИР</a></li>
                <li><a cap="Справка" ajax-href="<?php echo $this->url('help', array('action'=>'pages','id'=>'scientific_meetings')); ?>"  content="#help-content" href="#">Научные собрания / выставки</a></li>
                <li><a cap="Справка" ajax-href="<?php echo $this->url('help', array('action'=>'pages','id'=>'publication')); ?>"  content="#help-content" href="#">Публикации</a></li>
                <li><a cap="Справка" ajax-href="<?php echo $this->url('help', array('action'=>'pages','id'=>'honors')); ?>"  content="#help-content" href="#">Награды и поощрения</a></li>
                <li><a cap="Справка" ajax-href="<?php echo $this->url('help', array('action'=>'pages','id'=>'rucovodstvonirs')); ?>"  content="#help-content" href="#">Руководство НИРС</a></li>
            </ul>
        </div>
    <div class="span3">
            <h3>План</h3>
            <ul>
                <li><a cap="Справка" ajax-href="<?php echo $this->url('help', array('action'=>'pages','id'=>'document_plan')); ?>"  content="#help-content" href="#">Тематический план НИР</a></li>

            </ul>
        </div>

    </div>
<hr>

<div class="span12" id="help-content">

</div>
