<script type="application/javascript" src="/js/Archive/API.js"></script>
<script type="application/javascript" src="/js/API.js"></script>
<h1>Архив</h1>

<hr>
<div class="well">
    <p>
        Для начала работы с аривом выберите интересующий вас год.
    </p>
    <p>
        Для того чтобы выйти из Архива перейдите в "личный кабинет".
    </p>
    <div class="controls controls-row">
        <div class="span5">
            <select name="year">
                <option selected>2013</option>
            </select>
        </div>
    </div>
    </form>
</div>
<hr>
<div id="history_content" class="controls-row">

    <div class="alert alert-info">
        Интересующие вас таблицы выберайте в левом меню.
    </div>


</div>
