<h1>Контакты</h1>
<!--<div class="row">-->
<!--    Техническая поддержка: Dimajolkin@yandex.ru-->
<!--    Если у вас что то не работает, пишите.-->
<!--</div>-->
<div class="row">
    <table class="table">
        <tr>
            <td>Исакова Любовь Александровна<br>
                <i>Начальник отдела сопровождения научных исследований</i>
            </td>
            <td>
                <a  href="mailto:nauka@ksu.edu.ru" >
                    nauka@ksu.edu.ru
                </a>
            </td>
        </tr>

        <tr>
            <td>
                Дмитренко Екатерина Рудольфовна<br>
              <i>Специалист по УМР отдела сопровождения научных исследований</i>
            </td>
            <td>
                <a  href="mailto:conf@ksu.edu.ru" >
                conf@ksu.edu.ru
                </a>
            </td>
        </tr>

        <tr>
            <td>
                Ёлкин Дмитрий Владимирович<br>
              <i>Программист
              </i>
            </td>
            <td>
                <a  href="mailto:dimajolkin@yandex.ru" >
                    dimajolkin@yandex.ru
                </a>
            </td>
        </tr>
    </table>
</div>