<h1>Документ</h1>
<!---->
<!--<div class="row-fluid" id="list_file">-->
<!---->
<!--    <label class="radio inline">-->
<!--        <input type="radio" id="inlineCheckbox3" name="file" value="reports_nid">-->
<!--    </label>-->
<!---->
<!--    <label class="radio inline">-->
<!--        <input type="radio" id="inlineCheckbox3" name="file" value="reports_rid">-->
<!--    </label>-->
<!---->
<!--    <label class="radio inline">-->
<!--        <input type="radio" id="inlineCheckbox1" name="file" value="plan_nid">-->
<!--    </label>-->
<!---->
<!--    <label class="radio inline">-->
<!--        <input type="radio" id="inlineCheckbox2" name="file" value="plan_rid">-->
<!--    </label>-->
<!---->
<!--</div>-->

<div id="sys_msg">

</div>

<div class="tabbable" style="margin: 0px;">
    <ul class="nav nav-tabs">

        <?php foreach($tabs as $tab =>$param): ?>
            <li class="<?php echo $param['active']; ?>" >
                <a href="#<?php echo $tab; ?>"   data-toggle="tab">
                    <?php echo $param['name']; ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
    <div class="tab-content">
        <?php foreach($tabs as $tab =>$param): ?>
            <div class="tab-pane <?php echo $param['active']; ?>" id="<?php echo $tab; ?>" style="overflow: hidden;height: 100%;position: static;">
                <div class="row-fluid">

                    <h3 align="center"><?php echo $param['name']; ?></h3>
                        <p align="center">
                            Нажмите для скачивания.
                        </p>
                        <button
                            action="download"
                            value="<?php echo $param['type']; ?>"
                            class="btn btn-large" style="width: 100%" type="submit">
                            <i class="glyphicon-save"></i>
                            Скачать
                        </button>



                </div>
            </div>
        <?php endforeach; ?>

    </div>
</div>




<!--
<div class="row-fluid" id="document_content">
    <div class="controls controls-row" id="doc_interfase">

         <div id="btn-panel-download" class="btn-group span4" style="display: none" >
            <div id="document_download" class="btn btn-primary">Скачать документ</div>
            <div id="document_refresh" class="btn btn-primary"><i class="icon-white icon-refresh"></i></div>

        </div>

        <button type="button" id="document_generate" class="btn btn-success span4" style="display: none" >Сгенерировать</button>

        <div id="inf_file" class="span2 hidden">
            <div>Размер файла<p id="file_size"></p></div>
            <div>Дата создания:<p id="file_date"></p></div>
        </div>

    </div>

</div>
-->