<h1>Восстановление пароля</h1>

<?php print $this->showMessages(); ?>

<div class="row-fluid">
    <p>Для восстановления пароля введите Почтовый ящик который вы указали при регистрации на него придёт письмо с паролем.</p>


    <form method="post">
        <div class="row-fluid">
            <div class="control-group span4">
                <label class="control-label" for="inputIcon">Email</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-envelope"></i></span>
                        <input class="span12" name="email" type="text">
                    </div>
                </div>
            </div>
            <div class="control-group span4">
                <label class="control-label" for="inputIcon">Login</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-user"></i></span>
                        <input class="span12" name="login" type="text">
                    </div>
                </div>
            </div>
        </div>
        <button class="btn btn-primary btn-large" type="submit">Отправить запрос</button>
    </form>



</div>
<!--    <div class="control-group">-->
<!--        <div class="controls">-->
<!---->
<!--            <input type="password" id="password"  class="span2" placeholder="Почтовый ящик">-->
<!--            <button class="btn btn-success">Отправить</button>-->
<!---->
<!--        </div>-->
<!---->
<!---->
<!---->
<!--    </div>-->
