


<h1>Формирование отчёта</h1>

<script type="application/javascript" src="/js/Admin/reports.js"></script>

<div class="controls controls-row">
    <div class="span3">

            <select id="facultets">
                <?php foreach($facult as $fac): ?>
                    <option name="<?php echo $fac->id; ?>"><?php echo $fac->name; ?> </option>

                <?php endforeach; ?>
            </select>

    </div>
    <div class="span3">

            <select id="tables">
                <?php foreach($tables as $obj): ?>
                    <option name="<?php echo $obj->id; ?>"><?php echo $obj->menu; ?> </option>

                <?php endforeach; ?>
            </select>

    </div>
    <div class="span3">

        <button class="btn btn-primary" id="document_select">Проверить</button>

    </div>

</div>
<hr>
<div class="row-fluid">

    <div class="controls controls-row">

        <div class="controls controls-row" id="doc_interfase">

            <!--        <div id="btn_group_download" class="btn-group span4 hidden">-->
            <!--        <button type="button" id="download" class="btn btn-primary span3" data-loading-text="Loading...">Скачать Документ</button>-->
            <!--        <button type="button" id="generate" class="btn btn-primary span1" data-loading-text="Loading..."><i class="icon-refresh"></i></button>-->
            <!--        </div>-->
            <div id="btn-panel-download" class="btn-group span4" style="display: none" >
                <div id="document_download" class="btn btn-primary">Скачать документ</div>
                <div id="document_refresh" class="btn btn-primary"><i class="icon-white icon-refresh"></i></div>

            </div>

            <button type="button" id="document_generate" class="btn btn-success span4" style="display: none" >Сгенерировать</button>

            <div id="inf_file" class="span2 hidden">
                <div>Размер файла<p id="file_size"></p></div>
                <div>Дата создания:<p id="file_date"></p></div>
            </div>

        </div>
    </div>


</div>
