<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('UNID'. $this->translate(''))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/anim.css')
    //    ->prependStylesheet($this->basePath() . '/css/doc.css')
    //     ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.css')
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.js')
        ->prependFile($this->basePath() . '/js/jquery.js')
        ->prependFile($this->basePath() . '/js/animation/load.js')
        ->prependFile($this->basePath().  '/js/message/message.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>
</head>
<body>

<div class="row">


    <div class="container">
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="brand" href="<?php echo $this->url('home');  ?>">UNID</a>
                    </div>

                </div>

            </div>
        <?php echo $this->content; ?>

    </div> <!-- /container -->

</div>
<footer>

    <div class="navbar">
        <div class="navbar-inner navbar-fixed-bottom">
            <div class="container">
                <div class="brand" href="#">

                    <p>&copy; 2013 - <?php echo date('Y'); ?> КГУ им. Н.А. Некрасова </p>
                </div>
                <?php if( isset($user) ): ?>
                    <div class="navbar-static-top">
                        <ul class="nav">

<!--                       <li><a href="--><?php //echo  $this->url('Autoriza',array('controller'=>'user','action'=>'kontact')); ?><!--" onclick=""><i class="icon-edit"></i>Контакты</a></li>-->


                            <!--                                <li  class="kaf_hidden" ><a href="#application"> <i class="icon-edit"></i>Администратор</a></li>-->

                        </ul>

                        <ul id="user_panel" class="nav pull-right" >
                            <li>
                                <div class="span2 pull-right">
                                    <p>Телефон: <b>39-16-10</b><br> Внутренний : <b>210</b></p>
                                </div>
                            </li>

                        </ul>

                    </div>
                <?php endif; ?> <!--  -->
            </div>

        </div>
    </div>

</footer>

<?php echo $this->inlineScript() ?>
</body>

</html>