<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
    //    ->prependStylesheet($this->basePath() . '/css/doc.css')
    //     ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.css')
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>
</head>
<body>

<div class="row">

    <div class="container">
        <?php if(isset($user)): ?>
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="brand" href="<?php echo $this->url('home');  ?>">UNID</a>
                        <?php if( isset($user) ): ?>
                            <div class="navbar-static-top">
                                <ul class="nav">
                                    <li  class="app_hidden" ><a href="<?php echo $this->url('user'); ?>" onclick=""><i class="icon-user"></i>Лич. кабинет</a></li>

                                    <li class="app_hidden dropdown">
                                        <a data-toggle="dropdown" class="dropdown-toggle" href="#home" >Планы и отчёты<b class="caret"></b></a>
                                        <ul id="menu_navbar" class="dropdown-menu">
                                            <li class="nav-header">Отчёт</li>
                                            <li><a href="<?php echo $this->url('user',array('controller'=>'Table','action'=>'append','id'=>1));?>">Тема НИР</a></li>

                                        </ul>
                                    </li>


                                    <?php if($user->in_vars('kafedra')):  ?>
                                        <li class="kaf_hidden dropdown">
                                            <a data-toggle="dropdown" class="dropdown-toggle" href="#home" >Кафедра<b class="caret"></b></a>
                                            <ul id="menu_navbar2" class="dropdown-menu">
                                                <li class="nav-header">Персонал</li>
                                                <li><a href="<?php echo $this->url('kafedra',array('controller'=>'kafedra','action'=>'personal')); ?>">Управление</a></li>
                                                <li class="nav-header">Отчёт</li>
                                                <li><a href="<?php echo $this->url('kafedra',array('controller'=>'Tablekafedra','action'=>'copy','id'=>11));?>">Тематический отчёт по НИД</a></li>
                                                <li><a href="<?php echo $this->url('kafedra',array('controller'=>'Tablekafedra','action'=>'list','id'=>12));?>" >Участие в научных собраниях</a></li>
                                                <li><a href="<?php echo $this->url('kafedra',array('controller'=>'Tablekafedra','action'=>'list','id'=>13));?>">Руководство НИРС</a></li>
                                                <li><a href="<?php echo $this->url('kafedra',array('controller'=>'Tablekafedra','action'=>'list','id'=>14));?>">Отчёт по РИД</a></li>
                                                <li><a href="<?php echo $this->url('kafedra',array('controller'=>'Tablekafedra','action'=>'list','id'=>15));?>">Повышение квалификации</a></li>
                                                <li class="divider"></li>
                                                <li class="nav-header">План</li>
                                                <li><a href="<?php echo $this->url('kafedra',array('controller'=>'Tablekafedra','action'=>'copy','id'=>16));?>" type='plan' base='plan_themenir'>Тематический план по НИД</a></li>
                                                <li><a href="<?php echo $this->url('kafedra',array('controller'=>'Tablekafedra','action'=>'copy','id'=>17));?>" type='plan' base='plan_sm'>Организация научных собраний</a></li>
                                                <!--                                                    <li><a href="#kaf_input" type='plan' base='training_1'>Повышение квалификации</a></li>-->
                                                <li><a href="<?php echo $this->url('kafedra',array('controller'=>'Tablekafedra','action'=>'list','id'=>9));?>" type='plan' base='plan_publication'>План РИД</a></li>
                                                <li><a href="<?php echo $this->url('kafedra',array('controller'=>'Tablekafedra','action'=>'list','id'=>10));?>" type='plan' base='training_1'>Диссертации</a></li>
                                                <li><a href="<?php echo $this->url('kafedra',array('controller'=>'Tablekafedra','action'=>'list','id'=>19));?>" type='plan' base='training_2'>Повышение квалификации</a></li>
                                                <li><a href="<?php echo $this->url('kafedra',array('controller'=>'Tablekafedra','action'=>'list','id'=>20));?>" type='plan' base='training_3'>Стажировки</a></li>
                                                <li><a href="<?php echo $this->url('kafedra',array('controller'=>'Tablekafedra','action'=>'list','id'=>21));?>" type='plan' base='training_4'>Переподготовка</a></li>

                                                <li class="divider"></li>
                                                <li><a href="<?php echo $this->url('kafedra',array('controller'=>'Document'));?>" base='get_file'>Формирование</a></li>
                                                <!--        <li class="divider"></li>
                                                        <li><a href="#input" base='archive'>Архив</a></li>
                                                 -->

                                            </ul>
                                        </li>
                                    <?php endif; ?>
                                    <!--   <li  class="kaf_hidden" ><a href="#application" catalog="Message" >Сообщения</a></li> -->
                                </ul>
                                <ul id="user_panel" class="nav pull-right" >
                                    <li class="divider-vertical pull-right"></li>
                                    <li class="dropdown">
                                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                            <?php echo $user->get('name');  ?>
                                            <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="<?php echo  $this->url('user'); ?>"><i class="icon-user"></i>Лич. кабинет</a></li>
                                            <li><a href="<?php echo  $this->url('user',array('controller'=>'user','action'=>'kontact')); ?>" onclick=""><i class="icon-edit"></i>Контакты</a></li>
                                            <li><a href="<?php echo  $this->url('help'); ?>"><i class="icon-ok"></i>Справка</a></li>
                                            <li class="divider"></li>
                                            <li><a href="<?php echo  $this->url('user',array('controller'=>'user','action'=>'exit')); ?>"><i class="icon-share"></i>Выход</a></li>
                                        </ul>
                                    </li>

                                </ul>

                            </div>
                        <?php endif; ?> <!--  -->
                    </div>

                </div>

            </div>
        <?php endif;    ?>

        <?php echo $this->content; ?>
        <hr>
        <footer>
            <p>&copy; 2013 - <?php echo date('Y'); ?> КГУ </p>
        </footer>
    </div> <!-- /container -->

</div>
<footer>


</footer>

<?php echo $this->inlineScript() ?>
</body>

</html>